version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: argon2_elixir
    versions:
    - 2.4.0
  - dependency-name: hackney
    versions:
    - 1.17.4
